# Generated by Django 3.0.1 on 2020-02-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_filminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filminfo',
            name='duration',
            field=models.IntegerField(verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='origin',
            field=models.CharField(max_length=20, verbose_name='发行国家'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='pic',
            field=models.ImageField(null=True, upload_to='img', verbose_name='电影图片'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='release',
            field=models.CharField(max_length=20, verbose_name='上映具体时间和地点'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='releasetime',
            field=models.CharField(max_length=20, verbose_name='上映日期'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='syncpsis',
            field=models.CharField(max_length=400, verbose_name='剧情介绍'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='title',
            field=models.CharField(max_length=40, verbose_name='电影名'),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='type',
            field=models.CharField(max_length=40, verbose_name='类型'),
        ),
    ]
