# Generated by Django 3.0.3 on 2020-02-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='CeleList',
        ),
    ]
