# Generated by Django 3.0.3 on 2020-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200221_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='电影名')),
                ('pic', models.CharField(max_length=100, verbose_name='照片')),
            ],
        ),
    ]
