# Generated by Django 3.0.3 on 2020-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_imglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filminfo',
            name='pic',
            field=models.CharField(default='null', max_length=100, verbose_name='电影图片'),
        ),
    ]
