# Generated by Django 3.0.3 on 2020-03-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200221_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('userpwd', models.CharField(max_length=100, verbose_name='登陆密码')),
            ],
        ),
    ]
